MIN_REGION_AREA = 200
MIN_ASPECT_RATIO_GROUP_TEXT = 7
MAX_ASPECT_RATIO_GROUP_TEXT = 10
MIN_NUMBER_OF_TEXT_IN_GROUP_TEXT = 10
TOP_VIEW_PROCESS_HORIZONTAL_PART = 0.4
TOP_VIEW_PROCESS_VERTICLE_PART = 0.4
TOP_VIEW_REMOVE_SMALL_PIC_MIN_SIZE = 150
TOP_VIEW_DILATION_HORIZONTAL_SIZE = 50
