# PRE PROCESS
TOP_VIEW_PROCESS_HORIZONTAL_PART = 0.4
TOP_VIEW_PROCESS_VERTICLE_PART = 0.4
TOP_VIEW_REMOVE_SMALL_PIC_MIN_SIZE = 100
TOP_VIEW_DILATION_HORIZONTAL_SIZE = 50
# GROUP TEXT
MIN_REGION_AREA_GROUP_TEXT = 200
MIN_NUMBER_OF_TEXT_IN_GROUP_TEXT = 10
MIN_ASPECT_RATIO_GROUP_TEXT = 6
MAX_ASPECT_RATIO_GROUP_TEXT = 10
# TEXT
TEXT_IMAGE_CROP_PADDING_SIZE = 0
MIN_ASPECT_RATIO_TEXT = 0.4
MAX_ASPECT_RATIO_TEXT = 1.2